language: en-AU
reviews:
  high_level_summary: true
  request_changes_workflow: false
  path_filters:
    - terraform/**
    - terraform-well-architected/**
    - cloudformation/**
    - charts/**
    - ecs/**
    - .github/**
